import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { db, eq, schema } from "@genmotion/db";
import { PAYWALL_STATUS, QUOTA_STATUS, PLUGIN_ALLOWANCE, isPaywallBody, isQuotaBody } from "@genmotion/shared";
import { dbReady, truncateAll } from "./helpers/db";
import { createOrg, createUser, setSubscription } from "./helpers/factories";
import { createSession, request, requestJson } from "./helpers/http";
import { exportState } from "../limits";

/**
 * Chat plugins.
 *
 * These are the only endpoints in the product that spend money per call, which
 * is why they are the only ones gated on `paid` outright. A Free org with
 * exports still left is refused here and nowhere else, so that asymmetry is
 * what most of this file pins: it is easy to "simplify" the route to the
 * export gate later and quietly hand the provider bill to anyone who signs up.
 *
 * The provider itself is stubbed. What is under test is the gate, the
 * bookkeeping and the response shape — not whether ElevenLabs is up.
 */

const VOICEOVER = "/api/plugins/voiceover";
const SFX = "/api/plugins/sfx";
const IMAGE = "/api/plugins/image";

/** A signed-in owner of a fresh org, with that org active on the session. */
async function signedIn() {
  const owner = await createUser();
  const { orgId } = await createOrg({ ownerId: owner.id });
  const session = await createSession(owner.id, orgId);
  return { orgId, userId: owner.id, session };
}

/** The same, already paying. */
async function paying() {
  const ctx = await signedIn();
  await setSubscription(ctx.orgId, {
    plan: "pro",
    status: "active",
    currentPeriodEnd: new Date(Date.now() + 30 * 86_400_000),
  });
  return ctx;
}

function calls(orgId: string) {
  return db
    .select()
    .from(schema.pluginCalls)
    .where(eq(schema.pluginCalls.organizationId, orgId));
}

/** Stand in for the provider without touching the network. */
function stubFetch(impl: () => Promise<Response>) {
  return vi.spyOn(globalThis, "fetch").mockImplementation(impl as typeof fetch);
}

describe.skipIf(!dbReady)("chat plugins", () => {
  beforeEach(truncateAll);
  afterEach(() => vi.restoreAllMocks());

  it("refuses an org that has never paid", async () => {
    const { session } = await signedIn();
    const { status, body } = await requestJson(VOICEOVER, {
      as: session,
      json: { text: "Welcome to GenMotion." },
    });

    expect(status).toBe(PAYWALL_STATUS);
    expect(isPaywallBody(body)).toBe(true);
    expect((body as { paywall: { reason: string } }).paywall.reason).toBe("plugin");
  });

  /**
   * The whole point of the decision. A Free org can still export; it cannot
   * still generate, because provider credit spent on an account that never
   * converts is money we do not get back.
   */
  it("refuses a Free org that has exports left", async () => {
    const { session, orgId } = await signedIn();
    // A brand-new org has its whole allowance — the export gate would allow it.
    expect((await exportState(orgId)).remaining).toBeGreaterThan(0);

    const { status, body } = await requestJson(IMAGE, {
      as: session,
      json: { prompt: "A neon control room at night" },
    });

    expect(status).toBe(PAYWALL_STATUS);
    expect((body as { paywall: { reason: string } }).paywall.reason).toBe("plugin");
  });

  it("spends nothing at the provider when it refuses", async () => {
    const spy = stubFetch(async () => new Response("nope", { status: 500 }));
    const { session, orgId } = await signedIn();

    await requestJson(VOICEOVER, { as: session, json: { text: "Hello there." } });

    expect(spy).not.toHaveBeenCalled();
    // A refusal is not a call, so it is not in the cost log either.
    expect(await calls(orgId)).toHaveLength(0);
  });

  it("answers a paying org with the generated bytes and logs the call", async () => {
    const audio = Buffer.from("ID3 pretend this is an mp3");
    stubFetch(
      async () =>
        new Response(new Uint8Array(audio), {
          status: 200,
          headers: { "content-type": "audio/mpeg" },
        }),
    );
    const { session, orgId, userId } = await paying();

    const res = await request(VOICEOVER, {
      as: session,
      json: { text: "Welcome to GenMotion." },
    });

    expect(res.status).toBe(200);
    expect(res.headers.get("content-type")).toBe("audio/mpeg");
    expect(Buffer.from(await res.arrayBuffer())).toEqual(audio);

    const [logged] = await calls(orgId);
    expect(logged).toMatchObject({
      organizationId: orgId,
      userId,
      plugin: "voiceover",
      integration: "elevenlabs",
      ok: true,
      bytes: audio.byteLength,
      // No `character-cost` header from the stub, so the script's length.
      units: "Welcome to GenMotion.".length,
      unit: "characters",
      costUsdMicros: "Welcome to GenMotion.".length * 300,
    });
  });

  it("gates sound effects the same way, and passes the options through", async () => {
    const { session: free } = await signedIn();
    const refused = await requestJson(SFX, { as: free, json: { text: "a soft whoosh" } });
    expect(refused.status).toBe(PAYWALL_STATUS);

    const audio = Buffer.from("ID3 whoosh");
    const spy = stubFetch(
      async () => new Response(new Uint8Array(audio), { status: 200, headers: { "content-type": "audio/mpeg" } }),
    );
    const { session, orgId } = await paying();
    const res = await request(SFX, {
      as: session,
      json: { text: "a soft airy whoosh, rising", durationSeconds: 1.5, loop: false },
    });
    expect(res.status).toBe(200);
    expect(Buffer.from(await res.arrayBuffer())).toEqual(audio);

    const [url, init] = spy.mock.calls[0]!;
    expect(String(url)).toContain("/v1/sound-generation?output_format=mp3_44100_128");
    expect(JSON.parse(String(init?.body))).toEqual({ text: "a soft airy whoosh, rising", duration_seconds: 1.5 });
    // Metered from the request when the provider did not say: 1.5s × 40.
    expect((await calls(orgId))[0]).toMatchObject({
      plugin: "sfx",
      integration: "elevenlabs",
      ok: true,
      units: 60,
      unit: "characters",
      costUsdMicros: 60 * 300,
    });
  });

  it("refuses once the month's meter is spent, before spending at the provider", async () => {
    const { session, orgId, userId } = await paying();
    // A month of sound effects already on the books, all successful.
    await db.insert(schema.pluginCalls).values(
      Array.from({ length: PLUGIN_ALLOWANCE.sfx }, () => ({
        organizationId: orgId,
        userId,
        plugin: "sfx",
        integration: "elevenlabs",
        ok: true,
        bytes: 1,
        ms: 1,
        units: 100,
        unit: "characters",
      })),
    );
    const spy = stubFetch(async () => new Response("should not be called", { status: 500 }));

    const { status, body } = await requestJson(SFX, { as: session, json: { text: "one more whoosh" } });
    expect(status).toBe(QUOTA_STATUS);
    expect(isQuotaBody(body)).toBe(true);
    expect((body as { quota: { meter: string; used: number } }).quota).toMatchObject({ meter: "sfx", used: PLUGIN_ALLOWANCE.sfx });
    expect(spy).not.toHaveBeenCalled();

    // Other meters are untouched: a voiceover still goes through.
    stubFetch(async () => new Response(new Uint8Array(Buffer.from("ID3")), { status: 200, headers: { "content-type": "audio/mpeg" } }));
    expect((await request(VOICEOVER, { as: session, json: { text: "Still fine." } })).status).toBe(200);
  });

  it("counts characters against the voiceover meter, and reports usage on /limits", async () => {
    const { session, orgId } = await paying();
    stubFetch(async () => new Response(new Uint8Array(Buffer.from("ID3")), { status: 200, headers: { "content-type": "audio/mpeg" } }));
    await request(VOICEOVER, { as: session, json: { text: "Twenty-two characters." } });
    const { body } = await requestJson("/api/billing/limits", { as: session });
    const usage = (body as { usage: { characters: { used: number; limit: number }; sfx: { used: number } } }).usage;
    expect(usage.characters).toEqual({ used: "Twenty-two characters.".length, limit: PLUGIN_ALLOWANCE.characters });
    expect(usage.sfx.used).toBe(0);
    // A script that would overrun what is left is refused whole.
    const huge = "x".repeat(PLUGIN_ALLOWANCE.characters);
    expect((await requestJson(VOICEOVER, { as: session, json: { text: huge.slice(0, 5000) } })).status).toBe(200);
    void orgId;
  });

  it("splits the month by member for the dashboard", async () => {
    const { session, orgId, userId } = await paying();
    stubFetch(async () => new Response(new Uint8Array(Buffer.from("ID3")), { status: 200, headers: { "content-type": "audio/mpeg" } }));
    await request(SFX, { as: session, json: { text: "a click" } });
    await request(VOICEOVER, { as: session, json: { text: "Ten chars." } });

    const { status, body } = await requestJson("/api/billing/plugin-usage", { as: session });
    expect(status).toBe(200);
    const usage = body as { sfx: { used: number }; members: { userId: string; characters: number; sfx: number; images: number }[] };
    expect(usage.sfx.used).toBe(1);
    expect(usage.members).toEqual([{ userId, name: expect.any(String), email: expect.any(String), characters: 10, sfx: 1, images: 0 }]);
    void orgId;
  });

  it("logs a provider failure too, with the error", async () => {
    stubFetch(async () => new Response("upstream is down", { status: 500 }));
    const { session, orgId } = await paying();

    const { status } = await requestJson(VOICEOVER, {
      as: session,
      json: { text: "Welcome to GenMotion." },
    });

    // A provider outage is ours to own, not the caller's request being wrong.
    expect(status).toBe(502);

    const [logged] = await calls(orgId);
    expect(logged?.ok).toBe(false);
    expect(logged?.bytes).toBe(0);
    expect(logged?.error).toContain("500");
  });

  /**
   * A refused prompt comes back from Gemini as a 200 with prose instead of an
   * image. That is the caller's to fix, so it must not be reported as an outage
   * — the agent can rewrite the prompt and try again, but only if it is told.
   */
  it("reports a refused image prompt as a bad request", async () => {
    stubFetch(
      async () =>
        new Response(
          JSON.stringify({ promptFeedback: { blockReason: "SAFETY" } }),
          { status: 200, headers: { "content-type": "application/json" } },
        ),
    );
    const { session } = await paying();

    const { status, body } = await requestJson(IMAGE, {
      as: session,
      json: { prompt: "something the model will not draw" },
    });

    expect(status).toBe(400);
    expect((body as { error: string }).error).toContain("SAFETY");
  });

  it("requires a session at all", async () => {
    const { status } = await requestJson(IMAGE, { json: { prompt: "anything at all" } });
    expect(status).toBe(401);
  });
});
