import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { db, eq, schema } from "@genmotion/db";
import { PAYWALL_STATUS, isPaywallBody } from "@genmotion/shared";
import { dbReady, truncateAll } from "./helpers/db";
import { createOrg, createUser, setSubscription } from "./helpers/factories";
import { createSession, request, requestJson } from "./helpers/http";
import { checkPaywall } from "../limits";

/**
 * Chat plugins.
 *
 * These are the only endpoints in the product that spend money per call, which
 * is why they are the only ones gated on `paid` rather than on `checkPaywall`.
 * An org inside its free week is refused here and nowhere else, so that
 * asymmetry is what most of this file pins: it is easy to "simplify" the route
 * to `checkPaywall` later and quietly give the trial away.
 *
 * The provider itself is stubbed. What is under test is the gate, the
 * bookkeeping and the response shape — not whether ElevenLabs is up.
 */

const VOICEOVER = "/api/plugins/voiceover";
const IMAGE = "/api/plugins/image";

/** A signed-in owner of a fresh org, with that org active on the session. */
async function signedIn() {
  const owner = await createUser();
  const { orgId } = await createOrg({ ownerId: owner.id });
  const session = await createSession(owner.id, orgId);
  return { orgId, userId: owner.id, session };
}

/** The same, already paying. */
async function paying() {
  const ctx = await signedIn();
  await setSubscription(ctx.orgId, {
    plan: "pro",
    status: "active",
    currentPeriodEnd: new Date(Date.now() + 30 * 86_400_000),
  });
  return ctx;
}

function calls(orgId: string) {
  return db
    .select()
    .from(schema.pluginCalls)
    .where(eq(schema.pluginCalls.organizationId, orgId));
}

/** Stand in for the provider without touching the network. */
function stubFetch(impl: () => Promise<Response>) {
  return vi.spyOn(globalThis, "fetch").mockImplementation(impl as typeof fetch);
}

describe.skipIf(!dbReady)("chat plugins", () => {
  beforeEach(truncateAll);
  afterEach(() => vi.restoreAllMocks());

  it("refuses an org that has never paid", async () => {
    const { session } = await signedIn();
    const { status, body } = await requestJson(VOICEOVER, {
      as: session,
      json: { text: "Welcome to GenMotion." },
    });

    expect(status).toBe(PAYWALL_STATUS);
    expect(isPaywallBody(body)).toBe(true);
    expect((body as { paywall: { reason: string } }).paywall.reason).toBe("plugin");
  });

  /**
   * The whole point of the decision. Every other gate in the app lets a trial
   * org through; this one does not, because provider credit spent on an account
   * that never converts is money we do not get back.
   */
  it("refuses an org that is still inside its free trial", async () => {
    const { session, orgId } = await signedIn();
    // A brand-new org is by definition mid-trial — checkPaywall would allow it.
    expect(await checkPaywall(orgId)).toBeNull();

    const { status, body } = await requestJson(IMAGE, {
      as: session,
      json: { prompt: "A neon control room at night" },
    });

    expect(status).toBe(PAYWALL_STATUS);
    expect((body as { paywall: { reason: string } }).paywall.reason).toBe("plugin");
  });

  it("spends nothing at the provider when it refuses", async () => {
    const spy = stubFetch(async () => new Response("nope", { status: 500 }));
    const { session, orgId } = await signedIn();

    await requestJson(VOICEOVER, { as: session, json: { text: "Hello there." } });

    expect(spy).not.toHaveBeenCalled();
    // A refusal is not a call, so it is not in the cost log either.
    expect(await calls(orgId)).toHaveLength(0);
  });

  it("answers a paying org with the generated bytes and logs the call", async () => {
    const audio = Buffer.from("ID3 pretend this is an mp3");
    stubFetch(
      async () =>
        new Response(new Uint8Array(audio), {
          status: 200,
          headers: { "content-type": "audio/mpeg" },
        }),
    );
    const { session, orgId, userId } = await paying();

    const res = await request(VOICEOVER, {
      as: session,
      json: { text: "Welcome to GenMotion." },
    });

    expect(res.status).toBe(200);
    expect(res.headers.get("content-type")).toBe("audio/mpeg");
    expect(Buffer.from(await res.arrayBuffer())).toEqual(audio);

    const [logged] = await calls(orgId);
    expect(logged).toMatchObject({
      organizationId: orgId,
      userId,
      plugin: "voiceover",
      integration: "elevenlabs",
      ok: true,
      bytes: audio.byteLength,
    });
  });

  it("logs a provider failure too, with the error", async () => {
    stubFetch(async () => new Response("upstream is down", { status: 500 }));
    const { session, orgId } = await paying();

    const { status } = await requestJson(VOICEOVER, {
      as: session,
      json: { text: "Welcome to GenMotion." },
    });

    // A provider outage is ours to own, not the caller's request being wrong.
    expect(status).toBe(502);

    const [logged] = await calls(orgId);
    expect(logged?.ok).toBe(false);
    expect(logged?.bytes).toBe(0);
    expect(logged?.error).toContain("500");
  });

  /**
   * A refused prompt comes back from Gemini as a 200 with prose instead of an
   * image. That is the caller's to fix, so it must not be reported as an outage
   * — the agent can rewrite the prompt and try again, but only if it is told.
   */
  it("reports a refused image prompt as a bad request", async () => {
    stubFetch(
      async () =>
        new Response(
          JSON.stringify({ promptFeedback: { blockReason: "SAFETY" } }),
          { status: 200, headers: { "content-type": "application/json" } },
        ),
    );
    const { session } = await paying();

    const { status, body } = await requestJson(IMAGE, {
      as: session,
      json: { prompt: "something the model will not draw" },
    });

    expect(status).toBe(400);
    expect((body as { error: string }).error).toContain("SAFETY");
  });

  it("requires a session at all", async () => {
    const { status } = await requestJson(IMAGE, { json: { prompt: "anything at all" } });
    expect(status).toBe(401);
  });
});
