// Auto-generated: contributor avatars for firecrawl/firecrawl (GitHub no longer exposes stargazer lists).
import a00 from "../assets/stargazers/00.jpg"; // nickscamara
import a01 from "../assets/stargazers/01.jpg"; // mogery
import a02 from "../assets/stargazers/02.jpg"; // rafaelsideguide
import a03 from "../assets/stargazers/03.jpg"; // abimaelmartell
import a04 from "../assets/stargazers/04.jpg"; // developersdigest
import a05 from "../assets/stargazers/05.jpg"; // amplitudesxd
import a06 from "../assets/stargazers/06.jpg"; // ericciarla
import a07 from "../assets/stargazers/07.jpg"; // ftonato
import a08 from "../assets/stargazers/08.jpg"; // delong3
import a09 from "../assets/stargazers/09.jpg"; // Chadha93
import a10 from "../assets/stargazers/10.jpg"; // tomsideguide
import a11 from "../assets/stargazers/11.jpg"; // tomkosm
import a12 from "../assets/stargazers/12.jpg"; // erikengervall
import a13 from "../assets/stargazers/13.jpg"; // rakshith48
import a14 from "../assets/stargazers/14.jpg"; // KrisOei
import a15 from "../assets/stargazers/15.jpg"; // calebpeffer
import a16 from "../assets/stargazers/16.jpg"; // PhantomInTheWire
import a17 from "../assets/stargazers/17.jpg"; // mattjoyce
import a18 from "../assets/stargazers/18.jpg"; // micahstairs
import a19 from "../assets/stargazers/19.jpg"; // Sanix-Darker
import a20 from "../assets/stargazers/20.jpg"; // hmishra2250
import a21 from "../assets/stargazers/21.jpg"; // JakobStadlhuber
import a22 from "../assets/stargazers/22.jpg"; // rishi-raj-jain
import a23 from "../assets/stargazers/23.jpg"; // rowinsg
import a24 from "../assets/stargazers/24.jpg"; // aparupganguly
import a25 from "../assets/stargazers/25.jpg"; // bexgboost
import a26 from "../assets/stargazers/26.jpg"; // claude
import a27 from "../assets/stargazers/27.jpg"; // devhims
import a28 from "../assets/stargazers/28.jpg"; // chand1012
import a29 from "../assets/stargazers/29.jpg"; // MonsterDeveloper
import a30 from "../assets/stargazers/30.jpg"; // snippet
import a31 from "../assets/stargazers/31.jpg"; // karansideguide
import a32 from "../assets/stargazers/32.jpg"; // RutamBhagat
import a33 from "../assets/stargazers/33.jpg"; // szepeviktor
import a34 from "../assets/stargazers/34.jpg"; // dtaivpp
import a35 from "../assets/stargazers/35.jpg"; // rafaelmmiller
import a36 from "../assets/stargazers/36.jpg"; // malisper
import a37 from "../assets/stargazers/37.jpg"; // charlietlamb
import a38 from "../assets/stargazers/38.jpg"; // rahul-firecrawl
import a39 from "../assets/stargazers/39.jpg"; // KentHsu
import a40 from "../assets/stargazers/40.jpg"; // yekkhan
import a41 from "../assets/stargazers/41.jpg"; // rhys-firecrawl
import a42 from "../assets/stargazers/42.jpg"; // jarrensj
import a43 from "../assets/stargazers/43.jpg"; // busaud
import a44 from "../assets/stargazers/44.jpg"; // he-yufeng
import a45 from "../assets/stargazers/45.jpg"; // s-smits
import a46 from "../assets/stargazers/46.jpg"; // wahpiangle
import a47 from "../assets/stargazers/47.jpg"; // Jeelislive
import a48 from "../assets/stargazers/48.jpg"; // chenxin-yan
import a49 from "../assets/stargazers/49.jpg"; // rombru
import a50 from "../assets/stargazers/50.jpg"; // anjor
import a51 from "../assets/stargazers/51.jpg"; // tak-s
import a52 from "../assets/stargazers/52.jpg"; // swyxio
import a53 from "../assets/stargazers/53.jpg"; // mayooear
import a54 from "../assets/stargazers/54.jpg"; // MAVRICK-1
import a55 from "../assets/stargazers/55.jpg"; // vishkrish200
import a56 from "../assets/stargazers/56.jpg"; // saivedant169
import a57 from "../assets/stargazers/57.jpg"; // Max17190
import a58 from "../assets/stargazers/58.jpg"; // mdp
import a59 from "../assets/stargazers/59.jpg"; // loorisr
import a60 from "../assets/stargazers/60.jpg"; // eltociear
import a61 from "../assets/stargazers/61.jpg"; // kevinswiber
import a62 from "../assets/stargazers/62.jpg"; // shwetd19
import a63 from "../assets/stargazers/63.jpg"; // simonha9

export const AVATARS: string[] = [a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a60, a61, a62, a63];
